// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCttuDafRjrumRiR7A81CPg73kdGAmy7lI',
    appId: '1:409979331712:web:513850da84e7a6541ab265',
    messagingSenderId: '409979331712',
    projectId: 'hospital-management-syst-55814',
    authDomain: 'hospital-management-syst-55814.firebaseapp.com',
    storageBucket: 'hospital-management-syst-55814.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf_cQjOV9N4Rf4Jvf5aGLwPIkb98ZzJ1k',
    appId: '1:409979331712:android:348478eef64838581ab265',
    messagingSenderId: '409979331712',
    projectId: 'hospital-management-syst-55814',
    storageBucket: 'hospital-management-syst-55814.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdvixVLa-nK2vc1W6CfZHXxEnUwIlUnuo',
    appId: '1:409979331712:ios:801b6e836b2e6fe81ab265',
    messagingSenderId: '409979331712',
    projectId: 'hospital-management-syst-55814',
    storageBucket: 'hospital-management-syst-55814.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdvixVLa-nK2vc1W6CfZHXxEnUwIlUnuo',
    appId: '1:409979331712:ios:801b6e836b2e6fe81ab265',
    messagingSenderId: '409979331712',
    projectId: 'hospital-management-syst-55814',
    storageBucket: 'hospital-management-syst-55814.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCttuDafRjrumRiR7A81CPg73kdGAmy7lI',
    appId: '1:409979331712:web:dccd2f6b5af5292d1ab265',
    messagingSenderId: '409979331712',
    projectId: 'hospital-management-syst-55814',
    authDomain: 'hospital-management-syst-55814.firebaseapp.com',
    storageBucket: 'hospital-management-syst-55814.firebasestorage.app',
  );
}
